/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
static yyconst short int yy_accept[321] =
    {   0,
        0,    0,   58,   57,   57,   57,   57,   46,   57,   57,
       27,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,    0,    0,   22,    0,
       41,   23,   25,   26,   24,   17,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   43,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   22,    0,    0,    0,   42,
        0,    0,    0,    0,    0,    0,   44,   45,    0,   37,

        0,   30,    0,    0,    0,    0,    0,   32,    0,    0,
        0,    0,    0,    0,    0,   39,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   21,    0,   18,   13,   16,
        0,    0,    0,    0,   36,    0,    0,    0,    0,    0,
        0,    0,    0,   35,    0,    0,    0,    0,    0,   11,
        0,    0,   34,    0,    0,    0,   19,    0,   14,    0,
        0,    0,    0,    0,   20,    0,    0,    0,    0,    0,
       31,    0,   38,    0,    0,    0,    0,    0,    0,    0,
       15,    0,    0,    0,    0,    0,   40,   20,   20,    0,
       33,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   12,    0,   53,    0,
        0,    0,   20,    0,   48,    0,   51,    0,    0,   47,
        0,    0,    0,    0,    0,    0,   56,    0,    2,    0,
       53,    0,   52,    0,   20,   20,   20,   20,   20,   20,
       48,   51,   29,   47,    0,    0,   50,    0,   54,   56,
        0,    0,    1,   52,    0,    0,   20,   20,   20,   20,
       20,   20,   20,   20,    0,   50,   54,    0,    0,   55,
       20,   20,   20,   20,   20,   20,   20,   20,   49,    0,
       55,   20,   20,   20,   20,   20,   20,   20,   20,    0,
       20,   20,   20,   20,   20,   20,   20,   20,    0,   28,

        8,   20,   10,   20,   20,   20,   20,   20,    9,    3,
       20,   20,    7,    6,   20,   20,   20,    4,    5,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    1,    5,    6,    1,    1,    1,    7,
        8,    9,    1,   10,    1,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,    1,   14,
       15,   16,    1,    1,   17,   18,   19,   20,   21,   22,
       21,   21,   23,   21,   21,   21,   21,   24,   25,   21,
       21,   26,   27,   28,   21,   21,   21,   29,   21,   21,
       30,    1,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   21,   42,   43,   44,   45,
       46,   47,   21,   48,   49,   50,   51,   52,   53,   54,
       21,   21,    1,   55,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3
    } ;

static yyconst short int yy_base[339] =
    {   0,
        0,    0,  835,  836,   29,   51,  825,  836,  818,  817,
      827,  815,   53,   57,   61,   68,   83,   94,  109,  115,
      120,  131,  147,  155,  161,  182,  228,  154,  161,  171,
      178,  199,  200,  214,   57,   75,  778,  778,    0,  818,
      836,  836,  836,  836,  836,  124,  217,  811,  147,  213,
      813,  216,  231,  226,  230,  243,  253,  244,  265,  260,
      269,  259,  275,  281,  285,  290,  297,  306,  303,  310,
      313,  327,  328,  330,  333,  340,  342,  345,  357,  358,
      362,  367,  374,  777,  773,    0,  813,   52,  809,  371,
      105,  383,  384,  388,  400,  404,  401,  405,  417,  410,

      414,  426,  427,  431,  432,  441,  453,  447,  470,  471,
      457,  467,  487,  491,  469,  473,  494,  493,  497,  509,
      526,  514,  519,  773,  785,  806,   64,  836,  521,  523,
      535,  536,  548,  800,  539,  553,  549,  562,  565,  569,
      797,  794,  566,  571,  795,  788,  575,  578,  592,  587,
      604,  785,  599,  601,  748,  756,  836,  608,  605,  617,
      776,  773,  626,  629,  770,  771,  761,  758,  622,  761,
      760,  755,  632,  642,  754,  753,  752,  638,  714,  722,
      639,  652,  749,   74,  747,  672,  654,    0,  150,  750,
      749,  744,   76,  743,   77,  655,  742,  139,  739,  738,

      737,  736,  140,  656,  710,  715,  659,  736,  731,  729,
      168,  725,  694,  728,  723,  723,  706,  669,  709,  693,
      199,  676,  210,  672,  212,  670,  644,  679,  836,  619,
      836,  629,  621,  619,  619,  593,  589,  559,  544,  185,
      836,  836,  685,  836,  569,  559,  553,  547,  541,  836,
      686,  519,  508,  836,  526,  303,  532,  498,  514,  473,
      413,  418,  415,  386,  412,  836,  836,  699,  405,  396,
      386,  386,  374,  376,  333,  308,  351,  349,  836,  717,
      836,  318,  331,  319,  324,  285,  257,  289,  287,  284,
      279,  422,  278,  438,  238,  257,  471,  485,  244,  242,

        0,  233,    0,  176,  181,  166,  158,  152,    0,    0,
      143,  491,    0,    0,  507,   98,   91,    0,    0,  836,
       96,  771,  774,   56,  777,  780,  783,  786,  789,  792,
      795,  798,  801,  804,  807,  810,  813,  816
    } ;

static yyconst short int yy_def[339] =
    {   0,
      320,    1,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  321,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  321,  321,  321,  321,  321,   27,   27,   27,
       27,   27,   27,   27,   27,   27,  320,  320,  322,  323,
      320,  320,  320,  320,  320,  320,  324,  320,   27,   27,
      320,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,  320,  320,  322,  323,  323,  320,   27,
      320,   27,   27,   27,   27,   27,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,  320,  320,  323,  320,  320,   27,   27,
       27,   27,   27,  320,   27,   27,   27,   27,   27,   27,
      320,  320,   27,   27,  325,  320,   27,   27,   27,   27,
       27,  320,   27,   27,  320,  320,  320,   27,   27,   27,
      326,  320,   27,   27,  327,  328,  329,  330,   27,  325,
      325,  331,   27,   27,  320,  320,  332,   27,  320,  320,
       27,   27,  320,  326,  333,   27,   27,  327,  327,  328,
      328,  320,  329,  320,  330,   27,  320,  331,  320,  334,

      335,  320,  332,   27,  320,  320,   27,  320,  320,  320,
      333,  320,  327,  320,  320,  320,  320,   27,  320,  320,
      320,  320,  334,  320,  335,  320,  320,   27,  320,  336,
      320,  320,  320,  337,  327,  327,  327,  327,  327,  327,
      320,  320,   27,  320,  320,  320,  320,  320,  320,  320,
       27,  336,  336,  320,  320,  337,  327,  327,  327,  327,
      327,  327,  327,  327,  320,  320,  320,   27,  320,  320,
      327,  327,  327,  327,  327,  327,  327,  327,  320,   27,
      320,  327,  327,  327,  327,  327,  327,  327,  327,  338,
      327,  327,  327,  327,  327,  327,  327,  327,  338,  338,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,    0,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320
    } ;

static yyconst short int yy_nxt[892] =
    {   0,
        4,    4,    4,    4,    5,    6,    4,    4,    7,    4,
        8,    4,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   17,   17,   17,   22,    4,
        4,   17,   23,   24,   25,   26,   27,   28,   17,   17,
       29,   17,   30,   31,   17,   17,   32,   33,   34,   35,
       17,   17,   36,   17,    4,   37,   39,  126,   47,   40,
       88,   38,   46,   46,   47,   48,   46,   46,   47,   48,
       46,   46,   47,   48,  157,  127,   50,   46,   46,   47,
       48,  209,   51,  215,  217,  184,   51,  193,  195,   81,
       51,   49,   46,   46,   47,   48,   82,   51,   49,   49,

       53,  319,   52,   46,   46,   47,   48,   46,  318,   49,
       49,   46,   51,   54,   83,   46,   91,   49,   46,   46,
       47,   48,   46,   51,   46,   46,   47,   48,   49,   46,
       46,   47,   48,   46,   46,  128,   55,   46,   51,   57,
       46,   46,   47,   48,   51,   58,  220,  227,   46,   51,
      198,  203,  213,   56,  315,   59,   46,   46,   47,   48,
       51,  189,  314,   46,   46,   46,   47,   48,  313,   46,
       46,   46,   47,   48,   46,  233,   51,  312,   46,  211,
       60,   49,   61,  311,   51,   46,  310,   62,   49,   49,
       51,   46,   46,   47,   48,   49,   70,   64,   73,   71,

       49,   46,   63,   49,   72,   49,   65,   49,  245,   46,
      221,   51,   49,   49,   49,   46,   74,  247,   75,  249,
       49,  223,   66,  225,   49,  262,   46,   46,   76,   48,
      263,   49,   90,   49,   49,  264,   46,   46,   46,   47,
       48,   49,   49,  309,   77,   78,   51,   49,   79,  300,
       49,  300,   49,   49,   80,   49,   49,   51,   49,  306,
       49,   92,   67,   93,   49,   49,   49,   49,   49,   49,
       68,   46,   49,   49,  305,   95,   94,   49,   49,   49,
       97,   69,   46,   49,   49,   49,   49,   49,  303,  301,
       98,  300,   96,  101,   49,   49,   49,   49,  298,   49,

      297,   49,   49,   49,  100,  296,   49,   49,   99,   49,
      270,   49,   49,   49,  256,   49,  102,   49,   49,   49,
      295,  103,   49,   49,   49,  291,  293,   49,   49,  282,
      284,   49,   49,  104,   49,  294,  106,   49,   49,   49,
       49,  105,  292,   49,   49,   49,  107,   49,   49,  109,
       49,  289,   49,  288,  108,   49,   49,  110,  287,   49,
      111,   49,   49,   49,   49,  113,   49,   49,  114,   49,
       49,  112,   49,  286,   49,   49,   49,  115,  285,   49,
       49,   49,  116,   49,   49,  284,   49,   49,  283,  119,
      118,   49,   49,   49,  117,   49,   49,  282,   49,   49,

       49,   49,  120,  122,   49,   49,  121,  269,   49,   49,
       49,   49,  281,   49,  123,   49,   49,   49,   49,  279,
       49,  131,   49,  134,   49,  129,   49,   49,  278,  302,
       49,  130,  132,  292,   49,   49,   49,   49,   49,   49,
      133,   49,   49,   49,   49,  304,   49,   49,   49,  294,
      277,   49,   49,   49,   49,  135,   49,   49,   49,   49,
       49,   49,  276,   49,  275,   49,   49,   49,   49,  136,
       49,  137,  138,   49,   49,   49,  141,  142,  307,   49,
       49,   49,  297,   49,   49,   49,  139,   49,  143,   49,
      140,   49,  308,  145,   49,   49,  298,  146,  316,   49,

       49,  144,  312,   49,   49,   49,   49,   49,  274,   49,
       49,   49,   49,   49,  317,   49,  273,  272,  315,  147,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
      148,   49,  152,   49,  271,   49,   49,  269,  253,   49,
       49,  150,  149,   49,   49,  151,   49,   49,   49,  253,
       49,   49,  248,   49,  267,   49,   49,   49,  153,  162,
       49,  154,   49,   49,  246,   49,  266,   49,   49,   49,
       49,  165,   49,   49,   49,  166,   49,  158,   49,   49,
      265,   49,   49,   49,  261,  159,  160,   49,   49,   49,
       49,   49,   49,  163,  260,   49,   49,  164,  175,   49,

       49,   49,   49,   49,   49,   49,   49,   49,  169,   49,
      176,   49,   49,   49,  259,   49,  258,   49,   49,   49,
       49,   49,   49,  173,   49,  174,   49,  257,   49,   49,
      256,   49,  232,   49,   49,   49,  254,  178,   49,   49,
       49,   49,   49,   49,  181,   49,   49,   49,  199,  253,
       49,   49,   49,  182,   49,  226,   49,   49,   49,   49,
       49,   49,  186,   49,   49,  187,   49,  196,   49,  204,
       49,   49,   49,   49,   49,   49,   49,  250,  212,   49,
       49,   49,   49,  248,   49,   49,   49,  246,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,  228,  207,

      218,   49,  235,   49,  219,   49,   49,   49,   49,   49,
      236,   49,   49,   49,   49,  243,  244,  216,  237,   49,
       49,   49,   49,  290,  251,   49,  238,   49,   49,  239,
      242,  268,   49,   49,  214,  241,  234,  240,   49,   49,
      232,   49,  208,  231,  230,  280,  229,  226,  225,  223,
      221,   49,   49,  219,  216,  214,  191,  191,  211,   49,
      208,  206,  205,  203,  201,  200,  198,  171,  171,  195,
       49,   86,  193,   86,   87,   87,   87,  170,  191,  170,
      183,  189,  183,  188,  185,  188,  190,  184,  190,  192,
      180,  192,  194,  179,  194,  197,  177,  197,  202,  172,

      202,  210,  171,  210,  222,  168,  222,  224,  167,  224,
      252,  161,  252,  255,   88,  255,  299,  156,  299,  155,
      127,   88,  125,  124,   91,   89,   88,   85,   84,   45,
       44,   43,   42,   41,  320,    3,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320

    } ;

static yyconst short int yy_chk[892] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    6,   88,  324,    6,
       88,    5,   13,   13,   13,   13,   14,   14,   14,   14,
       15,   15,   15,   15,  127,  127,   13,   16,   16,   16,
       16,  184,   13,  193,  195,  184,   14,  193,  195,   35,
       15,   35,   17,   17,   17,   17,   35,   16,  321,   35,

       15,  317,   14,   18,   18,   18,   18,   13,  316,   36,
       35,   14,   17,   16,   36,   15,   91,   36,   19,   19,
       19,   19,   16,   18,   20,   20,   20,   20,   36,   21,
       21,   21,   21,   46,   46,   91,   18,   17,   19,   20,
       22,   22,   22,   22,   20,   21,  198,  203,   18,   21,
      198,  203,  189,   19,  311,   22,   23,   23,   23,   23,
       22,  189,  308,   19,   24,   24,   24,   24,  307,   20,
       25,   25,   25,   25,   21,  211,   23,  306,   46,  211,
       23,   49,   23,  305,   24,   22,  304,   24,   28,   49,
       25,   26,   26,   26,   26,   29,   28,   25,   29,   28,

       49,   23,   24,   29,   28,   30,   25,   28,  221,   24,
      221,   26,   31,   30,   29,   25,   30,  223,   31,  225,
       31,  223,   26,  225,   30,  240,   47,   47,   31,   47,
      240,   31,   50,   32,   33,  240,   26,   27,   27,   27,
       27,   32,   33,  302,   32,   33,   47,   50,   34,  300,
       52,  299,   32,   33,   34,   50,   34,   27,   52,  296,
       54,   52,   27,   53,   55,   53,   50,   34,   54,   52,
       27,   47,   55,   53,  295,   55,   54,   56,   58,   54,
       57,   27,   27,   55,   53,   56,   58,   57,  293,  291,
       59,  290,   56,   62,   60,   57,   56,   58,  289,   59,

      288,   62,   60,   61,   61,  287,   57,   59,   60,   63,
      256,   61,   62,   60,  256,   64,   63,   63,   59,   65,
      286,   64,   61,   64,   66,  282,  284,   65,   63,  282,
      284,   67,   66,   65,   64,  285,   67,   69,   65,   67,
       68,   66,  283,   66,   70,   69,   68,   71,   68,   69,
       67,  278,   70,  277,   68,   71,   69,   70,  276,   68,
       71,   72,   73,   70,   74,   73,   71,   75,   74,   72,
       73,   72,   74,  275,   76,   75,   77,   75,  274,   78,
       72,   73,   76,   74,   77,  273,   75,   78,  272,   79,
       78,   79,   80,   76,   77,   77,   81,  271,   78,   79,

       80,   82,   80,   82,   81,   90,   81,  270,   83,   82,
       79,   80,  269,   90,   83,   81,   83,   92,   93,  265,
       82,   94,   94,   99,   90,   92,   93,   83,  264,  292,
       94,   93,   95,  292,   95,   97,   92,   93,   96,   98,
       96,   94,   95,   97,  100,  294,   96,   98,  101,  294,
      263,   99,  100,   95,   97,  101,  101,   96,   98,   99,
      102,  103,  262,  100,  261,  104,  105,  101,  102,  103,
       99,  104,  105,  104,  105,  106,  109,  110,  297,  102,
      103,  108,  297,  106,  104,  105,  106,  107,  111,  108,
      107,  111,  298,  113,  106,  107,  298,  114,  312,  111,

      108,  112,  312,  115,  109,  110,  107,  116,  260,  112,
      111,  115,  109,  110,  315,  116,  259,  258,  315,  115,
      112,  113,  115,  109,  110,  114,  116,  118,  117,  113,
      117,  119,  121,  114,  257,  118,  117,  255,  253,  119,
      113,  119,  118,  120,  114,  120,  118,  117,  122,  252,
      119,  120,  249,  123,  248,  129,  122,  130,  122,  136,
      121,  123,  120,  129,  247,  130,  246,  122,  121,  131,
      132,  139,  123,  135,  129,  140,  130,  131,  132,  121,
      245,  135,  133,  137,  239,  132,  133,  136,  131,  132,
      133,  137,  135,  137,  238,  136,  138,  138,  149,  139,

      143,  133,  137,  140,  138,  144,  136,  139,  143,  147,
      151,  140,  148,  144,  237,  138,  236,  147,  139,  143,
      148,  150,  140,  147,  144,  148,  149,  235,  147,  150,
      234,  148,  233,  153,  149,  154,  232,  154,  151,  159,
      150,  153,  158,  154,  158,  149,  151,  159,  174,  230,
      158,  160,  153,  160,  154,  227,  169,  151,  159,  160,
      163,  158,  163,  164,  169,  164,  173,  169,  163,  178,
      160,  164,  178,  181,  173,  169,  174,  226,  186,  163,
      178,  181,  164,  224,  174,  173,  182,  222,  187,  196,
      204,  178,  181,  207,  182,  174,  187,  196,  204,  182,

      196,  207,  213,  218,  220,  182,  186,  187,  196,  204,
      213,  218,  207,  228,  186,  218,  219,  217,  213,  243,
      251,  228,  218,  280,  228,  186,  213,  243,  251,  213,
      216,  251,  228,  268,  215,  214,  212,  213,  243,  251,
      210,  268,  209,  208,  206,  268,  205,  202,  201,  200,
      199,  280,  268,  197,  194,  192,  191,  190,  185,  280,
      183,  180,  179,  177,  176,  175,  172,  171,  170,  168,
      280,  322,  167,  322,  323,  323,  323,  325,  166,  325,
      326,  165,  326,  327,  162,  327,  328,  161,  328,  329,
      156,  329,  330,  155,  330,  331,  152,  331,  332,  146,

      332,  333,  145,  333,  334,  142,  334,  335,  141,  335,
      336,  134,  336,  337,  126,  337,  338,  125,  338,  124,
       89,   87,   85,   84,   51,   48,   40,   38,   37,   12,
       11,   10,    9,    7,    3,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1807006.l"
#define INITIAL 0
#line 7 "1807006.l"

#include<string.h>

 int    op1,op2,operand=0;
#line 675 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 13 "1807006.l"

#line 828 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 321 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 836 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "1807006.l"
{printf("include library functions\n");
			                              fprintf(yyout,"include library functions\n");}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 16 "1807006.l"
{printf("#define\n");
									fprintf(yyout,"define\n");}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "1807006.l"
{  op1 = atoi(yytext);
			                              operand = 1;
                                               //printf("%d ",op1);
                                                printf("Print result of addition\n");
					                 fprintf(yyout,"Print result of addition\n");
					                  }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 25 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                          				 //printf("%d ",op1);
                            				 printf("Print result of subtraction\n");
								fprintf(yyout,"Print result of subtraction\n");
								 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 31 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                           					//printf("%d ",op1);
                           			  printf("Print result of division\n");
							fprintf(yyout,"Print result of division\n");
							 }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 37 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                           				//printf("%d ",op1);
                            				 printf("Print result of multiplication\n");
								fprintf(yyout,"Print result of multiplication\n");
								 }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                           				//printf("%d ",op1);
                            				 printf("Print result of modulus\n");
								fprintf(yyout,"Print result of modulus\n");
								 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 49 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                           				//printf("%d ",op1);
                            				 printf("Print result of exponent\n");
								fprintf(yyout,"Print result of exponent\n");
								 }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                           				//printf("%d ",op1);
                            				 printf("Print result of LOGICAL AND\n");
								fprintf(yyout,"Print result of LOGICAL AND\n");
								 }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "1807006.l"
{  op1 = atoi(yytext);
			         				operand = 1;
                           				//printf("%d ",op1);
                            				 printf("Print result of LOGICAL OR\n");
								fprintf(yyout,"Print result of LOGICAL OR\n");
								 }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "1807006.l"
{printf("take input from the user");}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "1807006.l"
{printf("\nInteger type\n");
								fprintf(yyout,"Integer type\n");
                           				 }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "1807006.l"
{printf("\nBool type\n");
								fprintf(yyout,"Bool type\n");
                           				 }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "1807006.l"
{printf("\nFloating type\n");
								fprintf(yyout,"\nFloating type\n");
                           				 }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 81 "1807006.l"
{printf("Double type\n");
								fprintf(yyout,"\nDouble type\n");
                           				 }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "1807006.l"
{printf("\nCharcter type\n");
								fprintf(yyout,"Character type\n");
                           				 }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 90 "1807006.l"
{//char name[] = yytext;
									//if(strlen(name) == ',' || strlen(name) == '.')
  									   //name[strlen(name)-1] = '\0'; // removing the last character i
 									 //printf("%s\n",name);
								printf("variable %s ",yytext);
								fprintf(yyout,"variable %s \n",yytext);
                           				 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "1807006.l"
{
								printf("array variable %s \n",yytext);
								fprintf(yyout,"array variable %s \n",yytext);
                           				 }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 103 "1807006.l"
{printf("\nValue assignment in variable\n");
								fprintf(yyout,"\nValue assignment in variable\n");
                           				 }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 106 "1807006.l"
{fprintf(yyout,"This is a print command\n");
            						  printf("This is a print command\n");}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "1807006.l"
{printf("This is a multiple  line comment\n");
              						 fprintf(yyout,"This is a multiple line comment\n");}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 110 "1807006.l"
{printf("This is a single line comment\n");
             						  fprintf(yyout,"This is a single line comment\n");}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "1807006.l"
{printf("This is assign operator\n");
           						    fprintf(yyout,"This is assign operator\n");}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 116 "1807006.l"
{printf("This is greater than equal\n");
            					   fprintf(yyout,"This is greater than equal\n");}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 118 "1807006.l"
{fprintf(yyout,"This is less than equal\n");}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 120 "1807006.l"
{printf("This is not equal\n");
         					      fprintf(yyout,"This is not equal\n");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "1807006.l"
{printf("This is equal\n");
         					      fprintf(yyout,"This is equal\n");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 125 "1807006.l"
{printf("This is while loop\n");
               					fprintf(yyout,"This is while loop\n");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "1807006.l"
{printf("This is for loop\n");
							                                           fprintf(yyout,"This is for loop\n");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "1807006.l"
{printf("break statement\n");
              				 fprintf(yyout,"break statement\n");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 133 "1807006.l"
{printf("This is iff condition\n");
						//printf(yytext);
               					fprintf(yyout,"This is iff condition\n");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 137 "1807006.l"
{printf("This is else condition\n");
              				 fprintf(yyout,"This is else condition\n");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 139 "1807006.l"
{printf("This is else if condition\n");
              				 fprintf(yyout,"This is else if condition\n");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 141 "1807006.l"
{printf("This is then statement for if and elif condition\n");
             			  fprintf(yyout,"This is then statement for if and elif condition\n");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 144 "1807006.l"
{printf("Function definition\n");
              				 fprintf(yyout,"This is function definition\n");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 146 "1807006.l"
{printf("Return statement\n");
              				 fprintf(yyout,"Return statement\n");
						}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 149 "1807006.l"
{printf("addition operation\n");
					fprintf(yyout,"addition operation\n");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 151 "1807006.l"
{printf("subtraction operation\n");
					fprintf(yyout,"subtraction operation\n");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 153 "1807006.l"
{printf("multiplication operation\n");
					fprintf(yyout,"multiplication operation\n");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 155 "1807006.l"
{printf("division operation\n");
					fprintf(yyout,"division operation\n");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 157 "1807006.l"
{printf("exponent operation\n");
					fprintf(yyout,"exponent operation\n");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 159 "1807006.l"
{printf("Logical and\n");
					fprintf(yyout,"logical and\n");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 161 "1807006.l"
{printf("Logical or\n");
				fprintf(yyout,"logical or\n");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 163 "1807006.l"
{printf("Logical not\n");
				fprintf(yyout,"logical not\n");} 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 165 "1807006.l"
{printf("XOR OPERATION\n");
				fprintf(yyout,"XOR OPERATION\n");} 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 167 "1807006.l"
{printf("full stop for end statement\n");
				fprintf(yyout,"full stop for end statement\n");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 170 "1807006.l"
{printf("Logarithm function\n");
				fprintf(yyout,"Logarithm function\n");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 172 "1807006.l"
{printf("Exp function\n");
				fprintf(yyout,"Exp function\n");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 174 "1807006.l"
{printf("Power function\n");
					fprintf(yyout,"Power Function\n");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 176 "1807006.l"
{printf("Square root\n");
				fprintf(yyout,"Square root\n");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 178 "1807006.l"
{printf("Floor function\n");
					fprintf(yyout,"Floor function\n");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 180 "1807006.l"
{printf("Ceil function\n");
				fprintf(yyout,"Ceil function\n");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 182 "1807006.l"
{printf("Absolute function\n");
				      fprintf(yyout,"Absolute function\n");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 184 "1807006.l"
{printf("Sine function\n");
				fprintf(yyout,"Sine function\n");}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 187 "1807006.l"
{printf("Cosine function\n");
				fprintf(yyout,"Cosine function\n");}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 190 "1807006.l"
{printf("Tangent function\n");
				fprintf(yyout,"Tangent function\n");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 194 "1807006.l"
ECHO;
	YY_BREAK
#line 1297 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 321 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 321 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 320);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 194 "1807006.l"


int yywrap()
{
return 1;
}

int main()
{
extern FILE *yyin, *yyout;
yyin = fopen ("input.txt","r");
yyout = fopen("output.txt","w");
//yyin = fopen ("var.txt","r");
//yyout = fopen("var2.txt","w");

yylex();
return 0;

}